// This file is auto-generated by scripts/generate-version.js.
// Do not edit manually.

export interface AppVersionInfo {
  major: number;
  phase: number;
  commit: number;
  formatted: string;
}

export const APP_VERSION: AppVersionInfo = {
  "major": 0,
  "phase": 4,
  "commit": 9,
  "formatted": "0.4.9"
} as const;
