// This file is auto-generated by scripts/generate-version.js.
// Do not edit manually.

export interface AppVersionInfo {
  major: number;
  phase: number;
  commit: number;
  formatted: string;
}

export const APP_VERSION: AppVersionInfo = {
  "major": 0,
  "phase": 5,
  "commit": 0,
  "formatted": "0.5.0"
} as const;
